### ISSUE TITLE
ScrollTop float ?

### ISSUE THREAD

**Issue by note89** [debois/elm-dom#5]
When using `elm-dom` `scrollTop` the decoder fails silently. 
I had to use `int` instead of `float` to get this to work

scrollTop : JD.Decoder Int
scrollTop =
    JD.at [ "target", "scrollTop" ] JD.int

**Comment by aforemny** [comment]
I just ran into a similar issue, but for me it is working in some instances and in some not. I will test some more…

I am a bit surprised to find out that it does not work, because it seems like [it should](https://github.com/elm-lang/core/blob/master/src/Native/Json.js#L345). However, [MDN states](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTop) that is should be an integer.

**Comment by aforemny** [comment]
After some more testing, I can confirm that `scrollTop` works for me being `Float`. I am testing with Firefox 47.0.1 on Linux x86_64.

@note89: What browser and operating system are you experiencing the problem with?

The "similar issue" I mentioned before is some other problem with `scrollTop` that I have yet to figure out. Sometimes `scrollTop` reports an old value rather than the actual one. But let's not dive into that since it is unrelated to this particular issue.

**Comment by debois** [comment]
Any conclusions here? Should we switch the type?

**Comment by aforemny** [comment]
I think we should keep it `Float`. Looking at core's [Json.js](https://github.com/elm-lang/core/blob/master/src/Native/Json.js#L263), it is unclear to me how parsing `Float` could possibly fail when `Int` doesn't. There are [some](https://drafts.csswg.org/cssom-view/#extension-to-the-element-interface) [indications](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/_Q7A4AQBFKY) that scrollTop will return floating point numbers in the future.

**Comment by debois** [comment]
@note89: What's the concrete browser/OS combination where this fails?
